name: PR open

on:
  pull_request:
    types: [open]

jobs:
  release:
  # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: jitterbit/get-changed-files@v1
      
      - name: Print env
        run: cat ${GITHUB_EVENT_PATH}
        
      - name: Print files
        run: print ${{ steps.files.outputs.added_modified }}
        
      
